- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install ngix
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
    state: started
    enabled: yes
