- name: vars
  hosts: localhost
  connection: local
  vars: 
    courses: "DevOps with AWS"
    Duration: "140hrs"
    trainer: vineeth
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "courses is: {{courses}}, trainer is: {{trainer}}, Duraton is: {{ Drration }}"