- name: vars
  hosts: localhost
  connection: local
  vars: 
    courses: "DevOps with AWS"
    Duration: "140hrs"
    trained: vineeth
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "courses is: {{courses}}; trainer is: {{vineeth}}; Duraton is: {{140hrs}}"