- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your user name
    private: false

  - name: password
    prompt: please enter your password
    private: true

  task:
  - name: print info
    ansible.builtin.debug:
      msg: "user name is: {{ user name }}, password is: {{ password }}"
