- name: print username and password
  hosts: localhost
  connection: local

  vars_prompt:
    - name: username
      prompt: "please enter your user name"
      private: false

    - name: password
      prompt: "please enter your password"
      private: true

  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "user name is: {{ username }}, password is: {{ password }}"
