
- name: play level variables
  hosts: localhost
  connection: local 
  tasks:
  - name: print variables
    vars:
     course: Ansible
    ansible.builtin.debug:
      msg: "courses is: {{ course }}"