
- name: variable preference
  hosts: localhost
  connection: local

  vars:
    NAME: "Ansible from play"

  vars_files:
    - course.yaml

  vars_prompt:
    - name: NAME
      prompt: "please enter your name"
      private: false

  tasks:
    - name: print nam
      vars:
        NAME: "ansible for task"
      ansible.builtin.debug:
        msg: "hi {{ NAME }}"