- name: demo on data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "DevsecOps with AWS" # string data type
    DURATION: 140 # int/number data type
    IS_LIVE: true # bool data type
    DETAILS: # MAP/dictionary 
      MONTHS: 4
      TRAINER: "shiva kumar"
    TOPICS: # list data type either -/[]
      - Linux
      - Shell
      - Ansible
  tasks:
  - name: print variables
    ansible.builtin.debug:
    msg: |
      program: {{PROGRAM}}
      duration: {{DURATION}}
      is_live: {{IS_LIVE}}
      details: {{DETAILS}}
      topics: {{TOPICS}}


