- name: printing facts
  hosts: local
  connection: local
  tasks:
    - name: print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"


    - name: check redhat or not
      ansible.builtin.debug:
        msg: "yes. its RedHat package manager "
      when: ansible_facts.os_family == "RedHat"

    - name: check debian or not
      ansible.builtin.debug:
        msg: "yes. its dabian package manager "
      when: ansible_facts.os_family == "debian"