- name: ansible from command vs shell module
  hosts: local
  connection: local
  tasks:
  - name: command module test
    # ansible.builtin.command: cat etc/passwd | grep root   #this will not work
    ansible.builtin.shell: cat /etc/passwd | grep root

    register: users_output
