- name : Demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is the reserved key word to store data/string  in ansible
    loop:
    - vineeth
    - chintu
    - lemrog
    - annamarine
