- name : Demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - vineeth
    - chintu
    - lemrog
    - annamarine
