- name: installing the packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.debug.packages:
      name:
      state: present
    loop:
    - mysql
    - nginx
    - zip