- name: installing the packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: #/ list of map
    - {name: "mysql", state: "absent" } # map/dict
    - {name: "nginx ", state: "present" }
    - {name: "zip", state: "present" }
