- name: filters - demo
  hosts: local
  connection: local 
  vars:
    topics: linix, shell, terraform, ansible
    tagsMap:
      name: ansible
      projet: roboshop
      component: catalogue
    tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "projet",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]


  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "hi, vineeth kumar, {{GREETING | default('Good morning')}}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split (',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items}}"


  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict}}"


  - name: read students yaml
    ansible.builtin.set_fact:  #setting the variable dynamically
      student_yaml: "{{lookup('file', student.yaml) | from_yaml }}"

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json}}"