- name: filters - demo
  hosts: local
  connection: local 
  vars:
    topics: linix, shell, terraform, ansible
    tags:
      name: ansible
      projet: roboshop
      component: catalogue

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "hi, vineeth kumar, {{GREETING | default('Good morning')}}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split (',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items}}"