- name: error handling
  hosts: local
  connection: local
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: user-output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user-output}}"