- name: error handling
  hosts: local
  connection: local
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: True

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create user
    ansible.builtin.command: add user
    when: user_output !=0
    